<?php
/**
 * config.example.php — Configuration template for myDailyTasks
 *
 * ⚠️  DO NOT edit this file directly.
 *     Copy it to "config.php" and fill in your own values.
 *
 *     cp config.example.php config.php
 *
 * config.php is ignored by Git (.gitignore) to prevent exposing
 * your database credentials on GitHub.
 */

// ── Database ─────────────────────────────────────────────────
/** MySQL server host */
define('DB_HOST', 'localhost');

/** Database name */
define('DB_NAME', 'timetracking');

/** MySQL username — replace with your own */
define('DB_USER', 'your_username');

/** MySQL password — replace with your own */
define('DB_PASS', 'your_password');

/** Connection charset */
define('DB_CHARSET', 'utf8mb4');

// ── Application ──────────────────────────────────────────────
/** Application display name */
define('APP_NAME', 'myDailyTasks');

/** Application version */
define('APP_VERSION', '1.0.0');

/** Minimum task duration (in minutes) */
define('TASK_DURATION_MIN', 10);

/** Maximum task duration (in minutes) */
define('TASK_DURATION_MAX', 480);

/** Duration increment (in minutes) */
define('TASK_DURATION_STEP', 10);

/** Internal date format (database) */
define('DATE_FORMAT_DB', 'Y-m-d');

/** Display date format (user-facing) */
define('DATE_FORMAT_DISPLAY', 'd/m/Y');